export {default as Carousel} from './Carousel'
export {default as CTASection} from './CTASection'
export {default as DetailedProduct} from './DetailedProduct'
export {default as DetailsSection} from './DetailsSection'
export {default as Slider} from './Slider'